## articOs mkinitcpio.conf.d — archiso overlay
## Adds plymouth (splash) and zen-specific hooks

MODULES=(btrfs)
HOOKS=(base udev microcode plymouth archiso)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)
